In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.model_selection import train_test_split

from sklearn import set_config
set_config(transform_output = 'pandas')

In [2]:
data = pd.read_csv("data/feature-engine/boston.csv")
data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [3]:
x = data.drop('MEDV',axis=1)
y=data[['MEDV']]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=0)

In [4]:
from sklearn.preprocessing import KBinsDiscretizer
discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='uniform')

discretizer.fit_transform(X_train[['LSTAT','NOX','DIS']])
discretizer.transform(X_test[['LSTAT','NOX','DIS']])

C:\Users\kyse1\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:239: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


LSTAT  NOX  DIS
141    9.0  4.0  0.0
272    1.0  1.0  2.0
135    4.0  4.0  0.0
298    0.0  0.0  6.0
122    4.0  4.0  0.0
..     ...  ...  ...
323    2.0  2.0  3.0
192    0.0  1.0  4.0
117    2.0  3.0  1.0
47     4.0  1.0  4.0
172    3.0  2.0  1.0

[354 rows x 3 columns]

LSTAT  NOX  DIS
329    1.0  1.0  3.0
371    2.0  5.0  0.0
219    2.0  3.0  1.0
403    5.0  6.0  0.0
78     3.0  1.0  3.0
..     ...  ...  ...
4      1.0  1.0  4.0
428    5.0  6.0  0.0
385    8.0  6.0  0.0
308    0.0  3.0  1.0
5      0.0  1.0  4.0

[152 rows x 3 columns]

In [5]:
discretizer.bin_edges_

array([array([ 1.73 ,  5.255,  8.78 , 12.305, 15.83 , 19.355, 22.88 , 26.405,
              29.93 , 33.455, 36.98 ])                                       ,
       array([0.385 , 0.4336, 0.4822, 0.5308, 0.5794, 0.628 , 0.6766, 0.7252,
              0.7738, 0.8224, 0.871 ])                                       ,
       array([ 1.1742 ,  2.26943,  3.36466,  4.45989,  5.55512,  6.65035,
               7.74558,  8.84081,  9.93604, 11.03127, 12.1265 ])         ],
      dtype=object)

In [6]:
discretizer = KBinsDiscretizer(n_bins=10, encode='ordinal', strategy='quantile')

discretizer.fit_transform(X_train[['LSTAT','NOX','DIS']])
discretizer.transform(X_test[['LSTAT','NOX','DIS']])

LSTAT  NOX  DIS
141    9.0  7.0  0.0
272    3.0  2.0  6.0
135    7.0  7.0  2.0
298    1.0  0.0  9.0
122    7.0  6.0  2.0
..     ...  ...  ...
323    5.0  3.0  7.0
192    0.0  1.0  8.0
117    4.0  5.0  4.0
47     8.0  2.0  8.0
172    6.0  4.0  3.0

[354 rows x 3 columns]

LSTAT  NOX  DIS
329    2.0  2.0  7.0
371    4.0  7.0  0.0
219    4.0  5.0  5.0
403    8.0  8.0  1.0
78     5.0  1.0  7.0
..     ...  ...  ...
4      1.0  2.0  8.0
428    8.0  8.0  1.0
385    9.0  8.0  0.0
308    0.0  5.0  5.0
5      1.0  2.0  8.0

[152 rows x 3 columns]

In [7]:
tmp = discretizer.fit_transform(X_train[['LSTAT','NOX','DIS']])
tmp['LSTAT'].value_counts()

9.0    36
8.0    36
4.0    36
0.0    36
6.0    36
3.0    35
1.0    35
5.0    35
2.0    35
7.0    34
Name: LSTAT, dtype: int64

In [8]:
discretizer = KBinsDiscretizer(n_bins=10,encode='ordinal',strategy='kmeans')

discretizer.fit_transform(X_train[['LSTAT','NOX','DIS']])
discretizer.transform(X_test[['LSTAT','NOX','DIS']])

C:\Users\kyse1\anaconda3\Lib\site-packages\sklearn\preprocessing\_discretization.py:239: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(
C:\Users\kyse1\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\Users\kyse1\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(
C:\Users\kyse1\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1436: UserWarning: KMeans is known to have a 

LSTAT  NOX  DIS
141    9.0  5.0  0.0
272    1.0  2.0  2.0
135    4.0  5.0  0.0
298    0.0  0.0  6.0
122    4.0  5.0  0.0
..     ...  ...  ...
323    2.0  3.0  3.0
192    0.0  1.0  4.0
117    2.0  4.0  1.0
47     4.0  2.0  4.0
172    3.0  3.0  1.0

[354 rows x 3 columns]

LSTAT  NOX  DIS
329    1.0  2.0  3.0
371    2.0  6.0  0.0
219    2.0  4.0  2.0
403    5.0  7.0  0.0
78     3.0  1.0  3.0
..     ...  ...  ...
4      0.0  2.0  4.0
428    5.0  7.0  0.0
385    8.0  7.0  0.0
308    0.0  4.0  2.0
5      0.0  2.0  4.0

[152 rows x 3 columns]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3, random_state=0)

from sklearn.tree import DecisionTreeRegressor

discretizer=DecisionTreeRegressor(max_depth=5,random_state=0)

discretizer.fit(X_train[['LSTAT']], y_train)
X_train['LSTAT_tree'] = discretizer.predict(X_train[['LSTAT']])
X_test['LSTAT_tree'] = discretizer.predict(X_test[['LSTAT']])

DecisionTreeRegressor(max_depth=5, random_state=0)

In [10]:
X_train['LSTAT_tree'].unique()

array([13.5       , 26.10625   , 15.69615385, 27.84      , 16.75555556,
       20.66666667, 13.18297872, 32.425     , 27.15641026, 29.58235294,
       29.95      , 15.525     , 16.44444444, 23.925     , 50.        ,
       43.2375    , 22.15      , 33.13333333, 32.73333333, 21.1       ,
       23.7       ,  7.68      , 46.86666667, 20.25      , 26.9       ,
       23.05      , 20.6       , 30.3       ])